new-session -n $HOST
set -g history-limit 30000

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

set-option -g status-position top

set-option -g repeat-time 0

# Removes ESC delay
set -sg escape-time 0

# zss kinda tight
set-option -g default-shell $SHELL

# copy and paster set-option -g default-command
# "reattach-to-user-namespace -l zsh"
set-option -g default-command "reattach-to-user-namespace -l fish"

# look good set -g default-terminal "screen-256color"
set -g default-terminal "screen-256color"

set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g default-terminal "xterm-256color"

# act like GNU screen unbind C-b set -g prefix C-a

# a mouse set -g mode-mouse on setw -g mouse-select-window on setw -g
set -g mouse on
# set -g mouse-utf8 on
# set -g mouse-select-window on

set -g @resurrect-capture-pane-contents 'on'

set -g set-clipboard on

# act like vim 
setw -g mode-keys vi 
bind M-Left  select-pane -L 
bind M-Down select-pane -D 
bind M-Up select-pane -U
bind M-Right select-pane -R 
bind-key -r C-h select-window -t :- 
bind-key -r C-l select-window -t :+ 
unbind [ 
bind ` copy-mode 
unbind p 
bind p paste-buffer 
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
bind r source-file ~/.tmux.conf

# after copying to a tmux buffer, hit y again to copy to clipboard bind
# y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"

set -g @themepack 'powerline/block/cyan'

# Status Bar configs

## Online Status


# List of plugins
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'caiogondim/maglev'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# source /Users/angusp/.local/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf


