add_newline = true
scan_timeout = 5

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"
disabled = false

[[battery.display]]
threshold = 20
style = "bold red"

[kubernetes]
style = "bold blue"
disabled = false

[kubernetes.context_aliases]

[package]
disabled = false
display_private = true
symbol =  "📦 "
style = "bold 208"

[conda]
style = "blue"
